---

- name: provision token-generator-ldap
  hosts: all

  vars_files:
    - vars.yml

  roles:
    - epel
    - ntp
    - git
    - python_tools
    - nginx 
    - firewalld
    - token_generator_ldap
